apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: users-crud
data:
  db.name: cG9zdGdyZXM= # postgres
  db.username: cG9zdGdyZXM= # postgres
  db.password: cG9zdGdyZXM= # postgres
  db.host: cG9zdGdyZXMtcG9zdGdyZXNxbA== # postgres-postgresql
  db.port: NTQzMg== # 5432
